CPIS_COUNTRY_TO_CODE = {
    'Afghanistan, Islamic Rep. of': 'AF',
    'Albania': 'AL',
    'Algeria': 'DZ',
    'American Samoa': 'AS',
    'Andorra, Principality of': 'AD',
    'Angola': 'AO',
    'Anguilla': 'AI',
    'Antigua and Barbuda': 'AG',
    'Argentina': 'AR',
    'Armenia, Rep. of': 'AM',
    'Aruba, Kingdom of the Netherlands': 'AW',
    'Australia': 'AU',
    'Austria': 'AT',
    'Azerbaijan, Rep. of': 'AZ',
    'Bahamas, The': 'BS',
    'Bahrain, Kingdom of': 'BH',
    'Bangladesh': 'BD',
    'Barbados': 'BB',
    'Belarus, Rep. of': 'BY',
    'Belgium': 'BE',
    'Belize': 'BZ',
    'Benin': 'BJ',
    'Bermuda': 'BM',
    'Bhutan': 'BT',
    'Bolivia': 'BO',
    'Bonaire, St. Eustatius and Saba': 'BQ',
    'Bosnia and Herzegovina': 'BA',
    'Botswana': 'BW',
    'Brazil': 'BR',
    'British Indian Ocean Territory': 'IO',
    'British Virgin Islands': 'VG',
    'Brunei Darussalam': 'BN',
    'Bulgaria': 'BG',
    'Burkina Faso': 'BF',
    'Burundi': 'BI',
    'Cabo Verde': 'CV',
    'Cambodia': 'KH',
    'Cameroon': 'CM',
    'Canada': 'CA',
    'Cayman Islands': 'KY',
    'Central African Rep.': 'CF',
    'Chad': 'TD',
    'Chile': 'CL',
    'China, P.R.: Hong Kong': 'HK',
    'China, P.R.: Macao': 'MO',
    'China, P.R.: Mainland': 'CN',
    'Christmas Island': 'CX',
    'Cocos (Keeling) Islands': 'CC',
    'Colombia': 'CO',
    'Comoros, Union of the': 'KM',
    'Congo, Dem. Rep. of the': 'CD',
    'Congo, Rep. of': 'CG',
    'Cook Islands': 'CK',
    'Costa Rica': 'CR',
    'Croatia, Rep. of': 'HR',
    'Cuba': 'CU',
    'Curaçao, Kingdom of the Netherlands': 'CW',
    'Curaçao and Sint Maarten': 'CS',
    'Cyprus': 'CY',
    'Czech Rep.': 'CZ',
    "Côte d'Ivoire": 'CI',
    'Denmark': 'DK',
    'Djibouti': 'DJ',
    'Dominica': 'DM',
    'Dominican Rep.': 'DO',
    'Ecuador': 'EC',
    'Egypt, Arab Rep. of': 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea, Rep. of': 'GQ',
    'Eritrea, The State of': 'ER',
    'Estonia, Rep. of': 'EE',
    'Eswatini, Kingdom of': 'SZ',
    'Ethiopia, The Federal Dem. Rep. of': 'ET',
    'Falkland Islands (Malvinas)': 'FK',
    'Faroe Islands': 'FO',
    'Fiji, Rep. of': 'FJ',
    'Finland': 'FI',
    'France': 'FR',
    'French Polynesia': 'PF',
    'French Southern Territories': 'TF',
    'Gabon': 'GA',
    'Gambia, The': 'GM',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Gibraltar': 'GI',
    'Greece': 'GR',
    'Greenland': 'GL',
    'Grenada': 'GD',
    'Guadeloupe': 'GP',
    'Guam': 'GU',
    'Guatemala': 'GT',
    'Guernsey': 'GG',
    'Guiana, French': 'GF',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Guyana': 'GY',
    'Haiti': 'HT',
    'Holy See': 'VA',
    'Honduras': 'HN',
    'Hungary': 'HU',
    'Iceland': 'IS',
    'India': 'IN',
    'Indonesia': 'ID',
    'International Organizations': 'IO',
    'International Organizations and SEFER' : 'IO',
    'Iran, Islamic Rep. of': 'IR',
    'Iraq': 'IQ',
    'Ireland': 'IE',
    'Isle of Man': 'IM',
    'Israel': 'IL',
    'Italy': 'IT',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Jersey': 'JE',
    'Jordan': 'JO',
    'Kazakhstan, Rep. of': 'KZ',
    'Kenya': 'KE',
    'Kiribati': 'KI',
    "Korea, Dem. People's Rep. of": 'KP',
    'Korea, Rep. of': 'KR',
    'Kosovo, Rep. of': 'KS',
    'Kuwait': 'KW',
    'Kyrgyz Rep.': 'KG',
    "Lao People's Dem. Rep.": 'LA',
    'Latvia': 'LV',
    'Lebanon': 'LB',
    'Lesotho, Kingdom of': 'LS',
    'Liberia': 'LR',
    'Libya': 'LY',
    'Liechtenstein': 'LI',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Madagascar, Rep. of': 'MG',
    'Malawi': 'MW',
    'Malaysia': 'MY',
    'Maldives': 'MV',
    'Mali': 'ML',
    'Malta': 'MT',
    'Marshall Islands, Rep. of the': 'MH',
    'Martinique': 'MQ',
    'Mauritania, Islamic Rep. of': 'MR',
    'Mauritius': 'MU',
    'Mayotte': 'YT',
    'Mexico': 'MX',
    'Micronesia, Federated States of': 'FM',
    'Moldova, Rep. of': 'MD',
    'Monaco': 'MC',
    'Mongolia': 'MN',
    'Montenegro': 'ME',
    'Montserrat': 'MS',
    'Morocco': 'MA',
    'Mozambique, Rep. of': 'MZ',
    'Myanmar': 'MM',
    'Namibia': 'NA',
    'Nauru, Rep. of': 'NR',
    'Nepal': 'NP',
    'Netherlands Antilles': 'AN',
    'Netherlands, The': 'NL',
    'New Caledonia': 'NC',
    'New Zealand': 'NZ',
    'Nicaragua': 'NI',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'Niue': 'NU',
    'Norfolk Island': 'NF',
    'North Macedonia, Republic of': 'MK',
    'Norway': 'NO',
    'Not Specified (including Confidential)': 'NS',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Palau, Rep. of': 'PW',
    'Panama': 'PA',
    'Papua New Guinea': 'PG',
    'Paraguay': 'PY',
    'Peru': 'PE',
    'Philippines': 'PH',
    'Pitcairn Islands': 'PN',
    'Poland, Rep. of': 'PL',
    'Portugal': 'PT',
    'Puerto Rico': 'PR',
    'Qatar': 'QA',
    'Reunion': 'RE',
    'Romania': 'RO',
    'Russian Federation': 'RU',
    'Rwanda': 'RW',
    'Saint Helena': 'SH',
    'Saint Pierre and Miquelon': 'PM',
    'Samoa': 'WS',
    'San Marino, Rep. of': 'SM',
    'Saudi Arabia': 'SA',
    'Senegal': 'SN',
    'Serbia, Rep. of': 'RS',
    'Seychelles': 'SC',
    'Sierra Leone': 'SL',
    'Singapore': 'SG',
    'Sint Maarten, Kingdom of the Netherlands': 'SX',
    'Slovak Rep.': 'SK',
    'Slovenia, Rep. of': 'SI',
    'Solomon Islands': 'SB',
    'Somalia': 'SO',
    'South Africa': 'ZA',
    'South Sudan, Rep. of': 'SS',
    'Spain': 'ES',
    'Sri Lanka': 'LK',
    'St. Kitts and Nevis': 'KN',
    'St. Lucia': 'LC',
    'St. Vincent and the Grenadines': 'VC',
    'Sudan': 'SD',
    'Suriname': 'SR',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Syrian Arab Rep.': 'SY',
    'São Tomé and Príncipe, Dem. Rep. of': 'ST',
    'Taiwan Province of China': 'TW',
    'Tajikistan, Rep. of': 'TJ',
    'Tanzania, United Rep. of': 'TZ',
    'Thailand': 'TH',
    'Timor-Leste, Dem. Rep. of': 'TL',
    'Togo': 'TG',
    'Tokelau': 'TK',
    'Tonga': 'TO',
    'Trinidad and Tobago': 'TT',
    'Tunisia': 'TN',
    'Turkmenistan': 'TM',
    'Turks and Caicos Islands': 'TC',
    'Tuvalu': 'TV',
    'Türkiye, Rep of': 'TR',
    'US Pacific Islands': 'PI',
    'Uganda': 'UG',
    'Ukraine': 'UA',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'GB',
    'United States': 'US',
    'United States Virgin Islands': 'VI',
    'Uruguay': 'UY',
    'Uzbekistan, Rep. of': 'UZ',
    'Vanuatu': 'VU',
    'Venezuela, Rep. Bolivariana de': 'VE',
    'Vietnam': 'VN',
    'Wallis and Futuna Islands': 'WF',
    'West Bank and Gaza': 'PS',
    'Western Sahara': 'EH',
    'World': 'WR',
    'World Minus 25 Significant Financial Centers': 'WM',
    'Yemen, Rep. of': 'YE',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW'
}