DS_COUNTRY_TO_CODE = {
    "ARGENTINA": "AR",
    # "AUSTRALIA": "AU",
    "AUSTRIA": "AT",
    "BELGIUM": "BE",
    "BRAZIL": "BR",
    "CANADA": "CA",
    "CHILE": "CL",
    "COLOMBIA": "CO",
    "CZECH REP.": "CZ",
    "DENMARK": "DK",
    # "EGYPT": "EG",
    "FINLAND": "FI",
    "FRANCE": "FR",
    "GERMANY": "DE",
    "GREECE": "GR",
    "HONG KONG": "HK",
    "HUNGARY": "HU",
    # "INDIA": "IN",
    "INDONESIA": "ID",
    "ISRAEL": "IL",
    "ITALY": "IT",
    "JAPAN": "JP",
    "KOREA": "KR",
    "MALAYSIA": "MY",
    "MEXICO": "MX",
    "NETHERLAND": "NL",
    # "NEW ZEALAN": "NZ",
    "NORWAY": "NO",
    "PHILIPPINE": "PH",
    "POLAND": "PL",
    "PORTUGAL": "PT",
    "RUSSIA": "RU",
    "SINGAPORE": "SG",
    "SOUTH AFRI": "ZA",
    "SPAIN": "ES",
    "SWEDEN": "SE",
    "SWITZ": "CH",
    "THAILAND": "TH",
    "TURKEY": "TR",
    "UK": "GB",
    "US": "US",
    "VENEZUELA": "VE",
    "WORLD": "WR",
}
