WFE_COUNTRY_TO_CODE = {
    "Argentina": "AR",
    "Austria": "AT",
    "Belgium": "BE",
    "Brazil": "BR",
    "Canada": "CA",
    "Chile": "CL",
    "Colombia": "CO",
    "Czech Republic": "CZ",
    "Denmark": "DK",
    "Finland": "FI",
    "France": "FR",
    "Germany": "DE",
    "Greece": "GR",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Indonesia": "ID",
    "Israel": "IL",
    "Italy": "IT",
    "Japan": "JP",
    "Korea": "KR",
    "Malaysia": "MY",
    "Mexico": "MX",
    "Netherlands": "NL",
    "Norway": "NO",
    "Philippines": "PH",
    "Poland": "PL",
    "Portugal": "PT",
    "Russia": "RU",
    "Singapore": "SG",
    "South Africa": "ZA",
    "Spain": "ES",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Thailand": "TH",
    "Turkey": "TR",
    "United Kingdom": "GB",
    "United States": "US",
    "Venezuela": "VE"
}
