WFE_EXCHANGE_TO_CODE = {
    "Abu Dhabi Securities Exchange": "AE",
    "American Stock Exchange": "US",
    "Amman Stock Exchange": "JO",
    "Angolan Securities Exchange (BODIVA)": "AO",
    "Armenia Securities Exchange": "AM",
    "Astana International Exchange": "KZ",
    "ASX Australian Securities Exchange": "AU",
    "Athens Stock Exchange": "GR",
    "B3 - Brasil Bolsa Balcão": "BR",
    "Bahrain Bourse": "BH",
    "Baku Stock Exchange": "AZ",
    "Banja Luka Stock Exchange": "BA",
    "Barbados Stock Exchange": "BB",
    "BATS Global Markets": "US",
    "Beirut Stock Exchange": "LB",
    "Belarusian Currency and Stock Exchange": "BY",
    "Belgrade Stock Exchange": "RS",
    "Bermuda Stock Exchange": "BM",
    "BME Spanish Exchanges": "ES",
    "BME Spanish Exchanges Barcelona": "ES",
    "BME Spanish Exchanges Bilbao": "ES",
    "BME Spanish Exchanges Madrid": "ES",
    "Bolsa de Comercio de Rosario": "AR",
    "Bolsa de Comercio de Santiago": "CL",
    "Bolsa de Valores de Caracas": "VE",
    "Bolsa de Valores de Colombia": "CO",
    "Bolsa de Valores de Lima": "PE",
    "Bolsa Electronica de Chile": "CL",
    "Bolsa Latinoamericana de Valores (Latinex)": "DO",
    "Bolsa Mexicana de Valores": "MX",
    "Bolsa Nacional de Valores de Costa Rica": "CR",
    "Bolsa y Mercados Argentinos": "AR",
    "Borsa Istanbul": "TR",
    "Borsa Italiana": "IT",
    "Botswana Stock Exchange": "BW",
    "Boursa Kuwait": "KW",
    "Bourse de Casablanca": "MA",
    "Bourse de Montreal": "CA",
    "Bratislava Stock Exchange": "SK",
    "BRVM": "CI",
    "BSE India Limited": "IN",
    "Bucharest Stock Exchange": "RO",
    "Budapest Stock Exchange": "HU",
    "Bulgarian Stock Exchange": "BG",
    "Bursa Malaysia": "MY",
    "Canadian Securities Exchange": "CA",
    "Cayman Island Stock Exchange": "KY",
    "Chittagong Stock Exchange": "BD",
    "Colombo Stock Exchange": "LK",
    "Cyprus Stock Exchange": "CY",
    "Dar Es Salaam Stock Exchange": "TZ",
    "Deutsche Boerse AG": "DE",
    "Dhaka Stock Exchange": "BD",
    "Dubai Financial Market": "AE",
    "Eswatini Stock Exchange": "SZ",
    "Euronext": "EU",
    "Euronext Amsterdam": "NL",
    "Euronext Brussels": "BE",
    "Euronext Dublin": "IE",
    "Euronext Lisbon": "PT",
    "Euronext Oslo": "NO",
    "Euronext Paris": "FR",
    "FMDQ Group": "NG",
    "Ghana Stock Exchange": "GH",
    "Hanoi Stock Exchange": "VN",
    "Hochiminh Stock Exchange": "VN",
    "Hong Kong Exchanges and Clearing": "HK",
    "Indonesia Stock Exchange": "ID",
    "Iran Fara Bourse Securities Exchange": "IR",
    "Jamaica Stock Exchange": "JM",
    "Japan Exchange Group": "JP",
    "Japan Exchange Group Osaka": "JP",
    "Japan Exchange Group Tokyo": "JP",
    "Johannesburg Stock Exchange": "ZA",
    "Karachi Stock Exchange": "PK",
    "Kazakhstan Stock Exchange": "KZ",
    "Korea Exchange": "KR",
    "Ljubljana Stock Exchange": "SI",
    "LSE Group": "GB",
    "LSE Group London Stock Exchange": "GB",
    "Lusaka Securities Exchange": "ZM",
    "Luxembourg Stock Exchange": "LU",
    "Malta Stock Exchange": "MT",
    "MERJ Exchange Limited": "SC",
    "MICEX": "RU",
    "Montenegro Stock Exchange": "ME",
    "Moscow Exchange": "RU",
    "Muscat Stock Exchange": "OM",
    "Nairobi Securities Exchange": "KE",
    "Namibian Stock Exchange": "NA",
    "Nasdaq - US": "US",
    "Nasdaq Nordic and Baltics": "SE",
    "NASDAQ OMX Nordic Copenhagen": "DK",
    "NASDAQ OMX Nordic Helsinki": "FI",
    "NASDAQ OMX Nordic Iceland": "IS",
    "NASDAQ OMX Nordic Stockholm": "SE",
    "NASDAQ OMX Riga": "LV",
    "NASDAQ OMX Tallinn": "EE",
    "NASDAQ OMX Vilnius": "LT",
    "National Equities Exchange and Quotations": "CN",
    "National Stock Exchange of India": "IN",
    "Nigerian Exchange": "NG",
    "NYSE": "US",
    "NZX Limited": "NZ",
    "Pakistan Stock Exchange": "PK",
    "Palestine Exchange": "PS",
    "Philippine Stock Exchange": "PH",
    "Port Moresby Stock Exchange": "PG",
    "Prague Stock Exchange": "CZ",
    "Qatar Stock Exchange": "QA",
    "Rio de Janeiro Stock Exchange": "BR",
    "RTS Exchange": "RU",
    "Rwanda Stock Exchange": "RW",
    "Saudi Exchange (Tadawul)": "SA",
    "Shanghai Stock Exchange": "CN",
    "Shenzhen Stock Exchange": "CN",
    "Singapore Exchange": "SG",
    "SIX Swiss Exchange": "CH",
    "Stock Exchange of Mauritius": "MU",
    "Surabaya Stock Exchange": "ID",
    "Sydney Stock Exchange": "AU",
    "Taipei Exchange": "TW",
    "Taiwan Stock Exchange": "TW",
    "Tashkent Stock Exchange": "UZ",
    "Tehran Stock Exchange": "IR",
    "Tel-Aviv Stock Exchange": "IL",
    "The Egyptian Exchange": "EG",
    "The International Stock Exchange": "GG",
    "The Stock Exchange of Thailand": "TH",
    "TMX Group": "CA",
    "Trinidad and Tobago": "TT",
    "Tunis Stock Exchange": "TN",
    "Ukrainian Exchange": "UA",
    "Vienna Stock Exchange": "AT",
    "Warsaw Stock Exchange": "PL",
    "Zagreb Stock Exchange": "HR",
    "Zimbabwe Stock Exchange": "ZW"
}
